import sys

from pygame.color import THECOLORS

SCREEN_HEIGHT = 800
SCREEN_WIDTH = 800
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

FRAME_RATE = 120

COLOR_BLACK = THECOLORS["black"]
COLOR_WHITE = THECOLORS["white"]

COLOR_WALL = COLOR_BLACK
COLOR_OPEN_NODE = THECOLORS["green"]
COLOR_CLOSED_NODE = THECOLORS["red"]
COLOR_START_NODE = THECOLORS["orange"]
COLOR_END_NODE = THECOLORS["blue"]
COLOR_PATH_NODE = THECOLORS["magenta"]

NODE_TYPE = {
    'empty': COLOR_WHITE,
    'wall': COLOR_WALL,
    'open': COLOR_OPEN_NODE,
    'closed': COLOR_CLOSED_NODE,
    'start': COLOR_START_NODE,
    'end': COLOR_END_NODE,
    'path': COLOR_PATH_NODE,
}

NODES_FILE = 'data/obstacle.json'

MAX_SIZE = sys.maxsize
# not being used
# MIN_SIZE = - sys.maxsize - 1

NODE_STRAIGHT_DISTANCE = 1000000000
NODE_DIAGONAL_DISTANCE = 1.414213562 * NODE_STRAIGHT_DISTANCE
